---
- hosts: all
  tasks:
    - name: CPU Frequency
      lineinfile:
        path: /boot/config.txt
        regexp: '^arm_freq='
        line: 'arm_freq=850'
    - name: GPU Memory Split
      lineinfile:
        path: /boot/config.txt
        regexp: '^gpu_mem='
        line: 'gpu_mem=16'
    - name: SD RAM Frequency
      lineinfile:
        path: /boot/config.txt
        regexp: '^sdram_freq='
        line: 'sdram_freq=500'
    - name: CPU Core Frequence
      lineinfile:
        path: /boot/config.txt
        regexp: '^core_freq='
        line: 'core_freq=300'
    - name: Boot Delay (disable)
      lineinfile:
        path: /boot/config.txt
        regexp: '^boot_delay='
        line: 'boot_delay=0'
    - name: Disable splash screen
      lineinfile:
        path: /boot/config.txt
        regexp: '^disable_splash='
        line: 'disable_splash=1'
    - name: Turbo for first 60 seconds (won't disable warranty)
      lineinfile:
        path: /boot/config.txt
        regexp: '^initial_turbo='
        line: 'initial_turbo=60'
    - name: Reboot Raspberry PI's
      command: reboot
      async: 0
      poll: 0
