- name: discover swap status
  shell: cat /proc/swaps | wc -l
  register: swap_out

- name: disable swap if enabled
  shell: |
    dphys-swapfile swapoff
    dphys-swapfile uninstall
    systemctl disable dphys-swapfile
  when: swap_out.stdout != "1"

- name: enable memory cgroup
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^dwc(.*)$'
    line: 'cgroup_enable=memory cgroup_memory=1 dwc\1'
    backrefs: yes

# https://github.com/kubernetes/kubernetes/issues/71305#issuecomment-509394152
- name: use iptables-legacy
  alternatives:
    name: '{{ item.name }}'
    path: '{{ item.path }}'
  loop:
    - name: iptables
      path: /usr/sbin/iptables-legacy
    - name: ip6tables
      path: /usr/sbin/ip6tables-legacy
    - name: ebtables
      path: /usr/sbin/ebtables-legacy

- name: reboot host
  shell: sleep 2 && /sbin/shutdown -r now "Ansible reboot"
  async: 1
  poll: 0

- name: wait for host to come back up
  become: false
  wait_for_connection:
    delay: 15
    sleep: 2
    timeout: 120
