---
- name: Generate a token beforehand
  command: kubeadm token generate
  register: token_out

- name: Set token
  set_fact:
    token: "{{ token_out.stdout }}"

- name: Init the cluster
  command: kubeadm init --token {{ token }} --pod-network-cidr {{ pod_network_cidr }}
  register: init_out

- debug: var=init_out

- name: Ensure the .kube dir exists for root
  file: path=/root/.kube state=directory

- name: Copy in the kubernetes config to the root user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    owner: root
    group: root

- name: Ensure the .kube dir exists for pi
  file: path=/home/pi/.kube state=directory

- name: Copy in the kubernetes config to the pi user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/pi/.kube/config
    remote_src: yes
    owner: pi
    group: pi

- name: Enable CNI (weave)
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  register: cni_out

- debug: var=cni_out

- name: Wait for the Weave CNI pods to stabalize
  shell: kubectl get pods --all-namespaces=true | grep weave-net | grep Running | wc -l
  register: cni_test
  until: cni_test.stdout == '1'
  retries: 12
  delay: 10

- name: Wait for the DNS pods to stabalize
  shell: kubectl get pods --all-namespaces=true | grep kube-dns | grep Running | wc -l
  register: dns_test
  until: dns_test.stdout == '1'
  retries: 12
  delay: 10
