---
- name: Discover node status
  include_tasks: discover.yml

- name: Create the cluster
  include_tasks: init.yml
  when:
    - node == "master"
    - cluster != "initialized"
  tags:
    - init

- debug: var=node
- debug: var=cluster
- debug: var=token
- debug: var=master_ip
- debug: var=node_ip

- name: Join the cluster
  include_tasks: join.yml
  when:
    - node == "slave"
    - cluster != "joined"
    - token is defined and token.stdout != ""
    - master_ip is defined and master_ip != ""
  tags:
    - join
