---
- name: Discover node status
  include_tasks: discover.yml

- debug: var=node
- debug: var=cluster

- name: Create the cluster
  include_tasks: init.yml
  when:
    - node == "master"
    - cluster != "initialized"
  tags:
    - init

- name: Set the master information
  set_fact:
    master_ip: "{{ hostvars['node00'].node_ip }}"  # Need to be set after discovery
    token: "{{ hostvars['node00'].token }}"  # Need to be set after discovery/init

- debug: var=node_ip
- debug: var=master_ip
- debug: var=token

- name: Join the cluster
  include_tasks: join.yml
  when:
    - node == "slave"
    - cluster != "joined"
    - token is defined and token != ""
    - master_ip is defined and master_ip != ""
  tags:
    - join

- name: Discover node status again once everyone has joined
  include_tasks: discover.yml

- name: Show cluster status
  shell: kubectl get nodes
  register: nodes_out
  when:
    - node == "master"

- debug: var=nodes_out
