---
- name: Enable Flannel CNI
  shell: "curl -sSL https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml | sed 's/amd64/arm/g' | kubectl create -f -"
  register: cni_out

- debug: var=cni_out

- name: Wait for the Flannel CNI pods to stabalize
  shell: kubectl get pods --namespace=kube-system | grep kube-flannel | grep Running | wc -l
  register: cni_test
  until: cni_test.stdout == '1'
  retries: 12
  delay: 10

- name: Wait for the DNS pods to stabalize
  shell: kubectl get pods --namespace=kube-system | grep kube-dns | grep Running | wc -l
  register: dns_test
  until: dns_test.stdout == '1'
  retries: 12
  delay: 10
