---
- name: Change hostname to match node name
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update /etc/hosts as well
  lineinfile:
    path: /etc/hosts
    regexp: "^127.0.1.1\t.*$"
    line: "127.0.1.1\t{{ inventory_hostname }}"

- name: Ensure apt https exists
  package:
    name: apt-transport-https
    state: present

- name: Add in docker apt repo key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present

- name: Add in docker apt repo
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable
    state: present

- name: Add in k8s apt repo key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add in k8s apt repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Update apt repos
  apt:
    update_cache: yes

- name: Install docker-ce
  apt:
    name: docker-ce
    state: present

- name: Install k8s (common)
  apt:
    name: kubeadm
    state: present
    force: yes

- name: Discover swap status
  shell: cat /proc/swaps | wc -l
  register: swap_out

- name: Register swap status
  set_fact:
    swap_enabled: swap_out.stdout != "1"

- name: Disable swap if enabled
  shell: |
    dphys-swapfile swapoff
    dphys-swapfile uninstall
    update-rc.d dphys-swapfile remove
  when: swap_enabled

- name: Enable memory cgroup for k8s
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^dwc(.*)$'
    line: 'cgroup_enable=memory cgroup_memory=1 dwc\1'
    backrefs: yes

- name: Reboot host
  shell: sleep 2 && /sbin/shutdown -r now "Ansible reboot"
  async: 1
  poll: 0

- name: Wait for host to come back up
  become: false
  wait_for_connection:
    delay: 15
    sleep: 2
    timeout: 120
