---
- name: Ensure apt https exists
  package:
    name: apt-transport-https
    state: present

- name: Add in docker apt repo key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present

- name: Add in docker apt repo
  apt_repository:
    repo: deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable
    state: present

- name: Add in k8s apt repo key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add in k8s apt repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Update apt repos
  apt:
    update_cache: yes

- name: Install docker-ce
  apt:
    name: docker-ce
    state: present

- name: Install k8s (common)
  apt:
    name: kubeadm
    state: present
    force: yes

- name: Discover swap status
  shell: cat /proc/swaps | wc -l
  register: swap_out

- name: Register swap status
  set_fact:
    swap_enabled: swap_out == "2"

- name: Disable swap if enabled
  shell: |
    dphys-swapfile swapoff
    dphys-swapfile uninstall
    update-rc.d dphys-swapfile remove
  when: swap_enabled

- name: Enable memory cgroup for k8s
  lineinfile:
    path: /boot/cmdline.txt
    regexp: '^dwc(.*)$'
#    line: 'cgroup_enable=memory dwc\1'  # This can be enabled once 4.14 is on rpi
    line: 'cgroup_enable=cpuset cgroup_memory=1 dwc\1'
    backrefs: yes
