---
# A service bridges a set of pods to an external port on the cluster
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: nginx
    tier: web
  ports:
  - protocol: TCP
    port: 80  # Port the client connects to
    targetPort: 80  # Port on the Pod traffic is forwarded to
  type: NodePort  # A random high port will be allocated on all cluster nodes to this service
---
# A deployment contains the pod spec and replica config
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: nginx
    tier: web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      tier: web
  template:
    metadata:
      labels:
        app: nginx
        tier: web
    spec:
      containers:
      - name: webserver
        image: michaelrobbins/k8s-example-web:latest
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 2
        ports:
        - containerPort: 80
